"""add image metadata fields

Revision ID: be962dd770db
Revises: c516c8b49a9f
Create Date: 2026-07-11 22:40:38.236122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be962dd770db'
down_revision: Union[str, Sequence[str], None] = 'c516c8b49a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('image_format', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'image_format')
    op.drop_column('images', 'height')
    op.drop_column('images', 'width')
    # ### end Alembic commands ###
